# Generated by Django 2.1.7 on 2019-03-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='details',
            field=models.TextField(default='details'),
        ),
        migrations.AddField(
            model_name='property',
            name='mainDetails',
            field=models.TextField(default='Main Details'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyType',
            field=models.TextField(default='Property Type'),
        ),
        migrations.AddField(
            model_name='property',
            name='propertyYoutube',
            field=models.TextField(default='YouTube Link'),
        ),
        migrations.AddField(
            model_name='property',
            name='reference',
            field=models.TextField(default='Reference'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.TextField(default='Status'),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.TextField(default='Title'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(default='Address'),
        ),
    ]
