# Generated by Django 2.2 on 2019-04-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0002_auto_20190310_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='facebookLink',
            field=models.TextField(default='Facebook Link'),
        ),
        migrations.AddField(
            model_name='property',
            name='sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='details',
            field=models.TextField(default='Details'),
        ),
    ]
