# Generated by Django 2.2 on 2019-04-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0003_auto_20190406_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
