# Generated by Django 2.2 on 2019-05-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0004_property_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='featuredProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='proeprtyStatus',
            field=models.CharField(choices=[('forsale', 'FOR SALE'), ('pending', 'Pending Sale'), ('sold', 'SOLD')], default='forsale', max_length=10),
        ),
    ]
