# Generated by Django 2.2 on 2019-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0005_auto_20190502_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='proeprtyStatus',
            field=models.CharField(choices=[('forsale', 'For Sale'), ('pending', 'Pending Sale'), ('sold', 'Sold')], default='forsale', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(default='Property Type', max_length=10),
        ),
    ]
