# Generated by Django 2.2 on 2019-05-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0006_auto_20190502_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.AlterField(
            model_name='property',
            name='reference',
            field=models.CharField(default='Reference', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(default='Title', max_length=20),
        ),
    ]
