# Generated by Django 2.2 on 2019-05-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0007_auto_20190502_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='sqft',
            new_name='sqmt',
        ),
    ]
