# Generated by Django 2.2 on 2019-05-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0008_auto_20190502_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='proeprtyStatus',
            new_name='propertyStatus',
        ),
    ]
