# Generated by Django 2.2 on 2019-05-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0010_auto_20190502_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyStatus',
            field=models.CharField(choices=[('FOR SALE', 'For Sale'), ('FOR RENT', 'Pending Sale'), ('SOLD', 'Sold')], default='FOR SALE', max_length=10),
        ),
    ]
