# Generated by Django 2.2 on 2019-05-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listApp', '0011_auto_20190502_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
